name: "bpe2000-de-it_transformer"
joeynmt_version: "2.0.0"

data:
    train: "data/train.bpe2000-de-it"
    dev:   "data/dev.bpe2000-de-it"
    test:  "data/test.bpe2000-de-it" 
    dataset_type: "plain"
    src:
        lang: "de"
        level: "bpe"
        lowercase: False
        max_sent_length: 100
        voc_file: "data/vocab.bpe2000-de-it"
        tokenizer_type: "subword-nmt"
        tokenizer_cfg:
          codes: "data/bpe.codes.de-it.2000"
    trg:
        lang: "it"
        level: "bpe"
        lowercase: False
        max_sent_length: 100
        voc_file: "data/vocab.bpe2000-de-it"
        tokenizer_type: "subword-nmt"
        tokenizer_cfg:
          codes: "data/bpe.codes.de-it.2000"

testing:
    beam_size: 5            
    beam_alpha: 1.0

training:
    random_seed: 42
    optimizer: "adam"
    normalization: "tokens"
    learning_rate: 0.0003
    batch_size: 512          
    batch_type: "token"
    eval_batch_size: 256
    eval_batch_type: "token"
    scheduling: "plateau"
    lr_reduce_verbose: False
    patience: 8
    weight_decay: 0.0
    decrease_factor: 0.7
    early_stopping_metric: "ppl"
    epochs: 10
    validation_freq: 250
    logging_freq: 50
    eval_metric: "bleu"
    model_dir:  "models/bpe2000_de-it_model" 
    overwrite: True
    shuffle: True
    use_cuda: False          
    max_output_length: 100
    print_valid_sents: [0, 1, 2, 3, 4]
    label_smoothing: 0.3

model:
    initializer: "xavier_uniform"
    bias_initializer: "zeros"
    init_gain: 1.0
    embed_initializer: "xavier_uniform"
    embed_init_gain: 1.0
    tied_embeddings: False   
    tied_softmax: True
    encoder:
        type: "transformer"
        num_layers: 4
        num_heads: 2
        embeddings:
            embedding_dim: 256
            scale: True
            dropout: 0
        hidden_size: 256
        ff_size: 512
        dropout: 0
    decoder:
        type: "transformer"
        num_layers: 1
        num_heads: 2
        embeddings:
            embedding_dim: 256
            scale: True
            dropout: 0
        hidden_size: 256
        ff_size: 512
        dropout: 0